export const userSeeder = [
    {
      name: "Admin",
      email: "admin@admin.com",
      password: "password",
      city: "Mansoura",
      state: null,
      role: "admin",
    },
    {
      _id: "63701cc1f03239c72c000180",
      name: "Marilyn",
      email: "mdonlon1@hostgator.com",
      password: "XRYBnKAfm",
      city: "Zhanghekou",
      state: null,
      country: "CN",
      occupation: "Food Chemist",
      phoneNumber: "9981906117",
      role: "user",
    },
    {
      _id: "63701cc1f03239c72c000184",
      name: "Donelle",
      email: "dcrossgrove5@constantcontact.com",
      password: "Q81bu6JV",
      city: "São Jerônimo",
      state: null,
      country: "BR",
      occupation: "Chemical Engineer",
      phoneNumber: "8601650433",
      role: "user",
    },
    {
      _id: "63701cc1f03239c72c000186",
      name: "Paola",
      email: "pledger7@freewebs.com",
      password: "L6mw336",
      city: "Xian’an",
      state: null,
      country: "CN",
      occupation: "Senior Quality Engineer",
      phoneNumber: "2982518057",
      role: "user",
    },
    {
      _id: "63701cc1f03239c72c00018a",
      name: "Felice",
      email: "fleivesleyb@liveinternet.ru",
      password: "vDE7jo",
      city: "Hrušica",
      state: null,
      country: "SI",
      occupation: "Administrative Assistant III",
      phoneNumber: "2401478620",
      role: "agent",
    }
  ];